export const codeLines = [
  [
    { text: "import", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "React", type: "object" },
    { text: ", ", type: "plain" },
    { text: "{", type: "plain" },
    { text: " useState, useEffect", type: "function" },
    { text: " }", type: "plain" },
    { text: " ", type: "plain" },
    { text: "from", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "'react'", type: "string" },
    { text: ";", type: "plain" },
  ],
  [
    { text: "export", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "default", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "function", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "Hero", type: "function" },
    { text: "() ", type: "plain" },
    { text: "{", type: "plain" },
  ],
  [
    { text: "  const ", type: "keyword" },
    { text: "[count, setCount]", type: "plain" },
    { text: " = ", type: "plain" },
    { text: "useState", type: "function" },
    { text: "(", type: "plain" },
    { text: "0", type: "string" },
    { text: ");", type: "plain" },
  ],
  [
    { text: "  const ", type: "keyword" },
    { text: "[files, setFiles]", type: "plain" },
    { text: " = ", type: "plain" },
    { text: "useState", type: "function" },
    { text: "(", type: "plain" },
    { text: "[]", type: "string" },
    { text: ");", type: "plain" },
  ],
  [{ text: "  async function httpGetFiles() {", type: "function" }],
  [
    { text: "    const res = await fetch", type: "function" },
    { text: "httpGetFiles()", type: "string" },
    { text: ";", type: "plain" },
  ],
  [{ text: "    const files = await res.json();", type: "plain" }],
  [{ text: "    setFiles(files);", type: "function" }],
  [{ text: "  }", type: "plain" }],
  [
    { text: "  useEffect", type: "function" },
    { text: "(() => {", type: "plain" },
  ],
  [{ text: "    httpGetFiles();", type: "function" }],
  [{ text: "  }, []);", type: "plain" }],
  [
    { text: "  return", type: "keyword" },
    { text: " ", type: "plain" },
    { text: "(", type: "plain" },
  ],
  [{ text: "    <section>", type: "jsx" }],
  [
    { text: "      <h1>", type: "jsx" },
    { text: "Full Stack Developer", type: "string" },
    { text: "</h1>", type: "jsx" },
  ],
  [
    { text: "      <p>", type: "jsx" },
    {
      text: "Designing and developing",
      type: "string",
    },
    { text: "</p>", type: "jsx" },
  ],
  [
    { text: "      <button onClick=", type: "jsx" },
    { text: "{", type: "plain" },
    { text: "() => setCount(count + 1)", type: "function" },
    { text: "}", type: "plain" },
    { text: ">", type: "jsx" },
    { text: "Clicked ", type: "string" },
    { text: "{count}", type: "object" },
    { text: " times", type: "string" },
    { text: "</button>", type: "jsx" },
  ],
  [{ text: "    </section>", type: "jsx" }],
  [{ text: "  );", type: "plain" }],
  [{ text: "}", type: "plain" }],
];
