const designPackages = [
  {
    title: "Design Essentials",
    slug: "design-essentials",
    seoTitle:
      "Small Business Website Design Services | VRB Web Design & Development",
    seoDescription:
      "Small business website design services for businesses and early-stage brands needing a polished, user-focused visual foundation.",
    startingAt: "$1,200",
    timeline: "1-2 weeks",
    bestFor:
      "Small businesses or early-stage brands needing a polished website design foundation",
    description:
      "A focused website design package for small businesses, created to establish a polished visual direction, thoughtful user experience, and strong foundation for development.",
    deliverables: "Homepage & supporting page concept",
    features: [
      "Brand & design consultation",
      "Website structure & sitemap planning",
      "Responsive layout direction",
      "Typography & color system",
      "1 high-fidelity page design mockup",
      "UI style direction & visual hierarchy",
    ],
    type: "Design",
    whatsIncluded: [
      "Discovery & design consultation",
      "Sitemap & structure planning",
      "Typography & color direction",
      "Responsive layout planning",
      "1 high-fidelity page mockup",
      "Final exported design assets",
    ],
    whatsNotIncluded: ["development", "coding", "launch", "branding systems"],
    revisionLimits: "2 rounds of revisions",
    optionalAddOns: [
      "Additional page mockups",
      "Mobile-specific mockups",
      "Full UI design system",
      "Interactive prototypes",
      "Branding support",
      "Design-to-development handoff",
      "Additional revision rounds",
      "Social media/marketing assets",
    ],
    revisionAndHandoffSupport: "1 week design handoff support",
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
  },
  {
    title: "Design Foundation",
    slug: "design-foundation",
    seoTitle: "UX UI Design Services | VRB Web Design & Development",
    seoDescription:
      "UX UI design services for businesses needing a strategic, user-focused foundation with responsive layouts, visual systems, and high-fidelity designs.",
    startingAt: "$2,400",
    timeline: "2-4 weeks",
    bestFor:
      "Businesses looking for strategic UX/UI design before moving into development.",
    description:
      "Strategic UX/UI design services focused on creating a cohesive, scalable, and user-friendly website experience through thoughtful structure and visual design.",

    includedMockups: "2-4 high-fidelity page designs",
    features: [
      "In-depth brand & UX strategy session",
      "Full sitemap & user flow planning",
      "Responsive UI system",
      "Brand color palette & style direction",
      "Typography system & hierarchy",
      "2–4 high-fidelity page mockups",
      "Logo refinement or moodboard support if needed",
      "Design-to-development planning support",
    ],
    type: "Design",
    whatsIncluded: [
      "UX strategy & planning",
      "Sitemap & information architecture",
      "Responsive UI direction",
      "Typography & color system",
      "2–4 high-fidelity mockups",
      "Export-ready design assets",
      "Design handoff support",
    ],
    whatsNotIncluded: [
      "Website development/coding",
      "Advanced branding packages",
      "Custom illustrations or animation systems",
      "Copywriting/content creation unless discussed",
      "Additional page designs outside agreed scope",
      "Hosting or deployment services",
    ],
    revisionAndHandoffSupport: "1 week design handoff support",
    revisionLimits: "2 rounds of revisions",
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
    highlight: "Most Popular",
  },
  {
    title: "Design Signature",
    slug: "design-signature",
    seoTitle: "User Experience Design Services | VRB Web Design & Development",
    seoDescription:
      "User experience design services for businesses needing a customized, scalable digital experience with advanced UX strategy and interface design.",

    startingAt: "$4,000",
    timeline: "4-8 weeks",
    bestFor:
      "Businesses needing a fully customized user experience, UX/UI system, and premium digital design before development.",
    description:
      "Premium user experience design services combining UX strategy, visual identity, interface design, and interactive prototypes to create a cohesive and scalable digital experience.",
    includedMockups: "4–8 high-fidelity page or interface mockups",
    features: [
      "Advanced UX & brand strategy sessions",
      "Full sitemap & user journey planning",
      "Responsive UI & component system",
      "Complete typography & visual hierarchy system",
      "Advanced color palette & brand direction",
      "4–8 high-fidelity interface mockups",
      "Interactive prototype flows",
      "Design system documentation",
      "Developer handoff preparation",
      "Creative direction & refinement support",
    ],
    type: "Design",
    whatsIncluded: [
      "UX strategy & discovery",
      "Advanced information architecture",
      "Responsive UI system",
      "Interactive prototypes",
      "4–8 high-fidelity mockups",
      "Design system documentation",
      "Developer handoff support",
      "Final export-ready assets",
    ],
    whatsNotIncluded: [
      "Website development/coding",
      "Custom illustrations unless discussed",
      "Copywriting/content creation unless discussed",
      "Ongoing design retainers",
      "Additional interface designs outside approved scope",
      "Hosting or deployment services",
    ],
    revisionAndHandoffSupport: "2 weeks design handoff support",
    revisionLimits: "2 rounds of revisions",
    optionalAddOns: [
      "Additional interface mockups",
      "Motion/interaction design",
      "Advanced prototyping",
      "Brand identity expansion",
      "Design presentations/decks",
      "Design retainer support",
      "Developer collaboration sessions",
      "Mobile app interface concepts",
      "Social media/marketing assets",
      "Advanced accessibility reviews",
    ],
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
  },
];
export default designPackages;
