import { MdWeb, MdStar, MdBuild } from "react-icons/md";

export const PackageInfo = [
  {
    title: "Website Essentials",
    startingAt: "$2,800",
    timeline: "2 - 4 Weeks",
    bestFor: "Small businesses needing a polished online  presence",
    description:
      "A clean, professional website built to clearly present your business, build trust,and make it easy for potential clients to get in touch with you.",
    pages: "2-5",
    features: [
      "Responsive Design",
      "Custom designed aligned with your business",
      "Contact form with email integration",
      "Basic SEO setup",
      "Launch & Deployment setup",
    ],
    type: "website",
    icon: MdWeb,
    whatsIncluded: [
      "2-5 responsive web pages",
      "Custom homepage design",
      "Contact form integration",
      "Mobile & tablet optimization",
      "Basic SEO foundations",
      "Website Launch & deployment",
    ],
    whatsNotIncluded: [
      "Copywriting/content creation unless discussed",
      "Advanced SEO strategy",
      "Custom backend/dashboard systems",
      "Ongoing website maintenance",
      "Additional pages outside agreed scope",
    ],
    revisionLimits: "2 rounds of revisions",
    supportPeriod: "2 weeks post-launch support",
    optionalAddOns: [
      "Additional pages",
      "Copywriting support",
      "Blog Integration",
      "Booking Systems",
      "Ongoing Maintenance",
    ],
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
  },
  {
    title: "Professional Website",
    startingAt: "$5,500",
    timeline: "4-8 weeks",
    bestFor:
      "Growing businesses ready for a more strategic, scalable, and flexible online presence.",
    description:
      "A fully custom website designed to support growth through stronger strcutre, improved user experience, and expanded functionality.",
    pages: "Up to 10",
    features: [
      "Fully responsive custom design",
      "Form & Email integration",
      "SEO foundations included",
      "Branding & UX Consultation",
      "Light backend features such as newsletter signup, basic booking, or gated content areas",
    ],
    type: "website",
    highlight: "Most Popular",
    icon: MdStar,
    whatsIncluded: [
      "Up to 10 custom-designed pages",
      "Fully responsive website design",
      "UX & branding consultation",
      "Contact forms & email integrations",
      "SEO foundations setup",
      "Light interactive/backend functionality",
      "Website launch & deployment",
      "Mobile & tablet optimization",
      "Website planning & ux strategy",
    ],
    whatsNotIncluded: [
      "Advanced custom web applications",
      "Full dashboard/admin systems",
      "Custom payment platforms",
      "Complex membership systems",
      "Ongoing maintenance or content management",
      "Copywriting/content creation unless discussed",
    ],
    revisionLimits: "2 rounds of revisions",
    optionalAddOns: [
      "Additional pages",
      "Blog Integration",
      "Booking system expansion",
      "Copywriting support",
      "Advanced animations/interactions",
      "CMS Integration",
      "Ongoing maintenance plans",
      "Analytics & tracking setup",
      "Additional SEO optimization",
      "Email marketing Integration",
    ],
    supportPeriod: "30 days post-launch support",
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
  },
  {
    title: "Custom Platform",
    startingAt: "$12,000",
    timeline: "3-6 months || 8-24 weeks",
    bestFor:
      "Businesses requiring advanced functionality, custom workflows, or scalable platform architecture.",
    pages: "Up to 20",
    description:
      "A fully bespoke web platform designed around your business operations, workflows, and long-term scalability — ideal for projects that go beyond a traditional marketing website.",
    features: [
      "Custom frontend and backend architecture",
      "User accounts & authentication",
      "Database and API Integration",
      "Custom UI & platform experience",
      "Advanced functionality or custom workflows",
      "Ongoing collaboration and support options.",
      "Scalable platform structure",
    ],
    type: "website",
    icon: MdBuild,
    whatsIncluded: [
      "Up to 20 custom-designed pages/screens",
      "Fully responsive platform design",
      "Frontend & backend development",
      "Authentication & user account systems",
      "Database & API integrations",
      "Advanced workflows & custom functionality",
      "UX strategy & platform planning",
      "Website/platform deployment",
      "Scalable architecture planning",
    ],
    whatsNotIncluded: [
      "Third-party subscription costs",
      "Large-scale enterprise infrastructure",
      "Ongoing maintenance unless discussed",
      "Copywriting/content creation unless discussed",
      "Additional features outside approved scope",
      "External software licensing fees",
    ],
    revisionLimits: "2 revisions",
    optionalAddOns: [
      "Ongoing maintenance plans",
      "Advanced analytics & reporting",
      "Custom admin dashboards",
      "Membership/subscription systems",
      "Payment integrations",
      "Multi-user permissions",
      "Advanced SEO strategy",
      "Automation integrations",
      "API expansion",
      "Additional platform modules/features",
    ],
    supportPeriod:
      "30 days post-launch support. Significant feature or workflow changes after approval may require revised timelines or additional billing.",
    note: "Hosting, domains, and third-party subscription costs are not included unless otherwise discussed",
  },
];
