export const Retainer = [
  {
    title: "Mini",
    startingAt: "$400",
    timeline: "Monthly",
    bestFor: "Growing businesses",
    description:
      "Ongoing support and updates for your website, including content changes, security updates, and performance monitoring.",
    features: [
      "Up to 5 hours of support per month",
      "Content updates and edits",
      "Security monitoring and updates",
      "Performance optimization",
      "Priority support",
    ],
    type: "retainer",
    whatsIncluded: [
      "Up to 5 hours of support per month",
      "Content updates and edits",
      "Security monitoring and updates",
      "Performance optimization",
    ],
    revisionLimits: "N/A",
    supportPeriod: "Ongoing",
    optionalAddOns: [],
    note: "Monthly retainer for basic site support",
  },
  {
    title: "Boost",
    startingAt: "$1,200",
    timeline: "Quarterly",
    bestFor: "Ongoing support",
    description:
      "Comprehensive support and updates for your website every quarter, including content changes, security updates, and performance monitoring.",
    features: [
      "Up to 15 hours of support per quarter",
      "Content updates and edits",
      "Security monitoring and updates",
      "Performance optimization",
      "Priority support",
      "Quarterly performance reports",
    ],
    type: "retainer",
    whatsIncluded: [
      "Up to 15 hours of support per quarter",
      "Security monitoring and updates",
      "Quarterly performance reports",
    ],
    revisionLimits: "N/A",
    supportPeriod: "Ongoing",
    optionalAddOns: [],
    note: "Quarterly retainer with reporting",
  },
  {
    title: "Momentum",
    startingAt: "$4,800",
    timeline: "Annual",
    bestFor: "Scaling teams",
    description:
      "Full-year support and updates for your website, including content changes, security updates, performance monitoring, and strategic planning.",
    features: [
      "Up to 60 hours of support per year",
      "Content updates and edits",
      "Security monitoring and updates",
      "Performance optimization",
      "Priority support",
      "Quarterly performance reports",
      "Annual strategic planning session",
    ],
    type: "retainer",
    whatsIncluded: [
      "Up to 60 hours of support per year",
      "Security monitoring and updates",
      "Quarterly performance reports",
      "Annual strategic planning session",
    ],
    revisionLimits: "N/A",
    supportPeriod: "Annual",
    optionalAddOns: [],
    note: "Annual retainer for comprehensive ongoing support",
  },
];
